dist: xenial
language: node_js
os: linux

env:
  global:
  - CC_TEST_REPORTER_ID=ad774adde14659710627fa169c87f7366d0f3fdbdbdf8d18b5182ed3b6241c49
jobs:
  include:
    - node_js: '12'
cache:
  directories:
    - "node_modules"
services:
  - postgresql
install:
  - npm install

before_script:
  - psql -c 'create database todo_test;' -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD null;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_success:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - npm install -g serverless
  - export NODE_EVN=production && npm run build
deploy:
  provider: script
  script:
    - sls deploy
  skip_cleanup: true
  on: 
    branch: serverless

